
data_path: 'data/german_credit.csv' # path to the dataset csv-file
results_dir: 'final_results/german_data/german_balTestSet/' # directory to save the results
weight_idx: 1 # weight index for samples (1 in our runs)
testset_size: 0.3 # proportion of testset samples in the dataset (e.g. 0.3)
balance_bool: True # False = default (testset like trainset), True = balanced testset
models: # classifers used for training
  Decision Tree: 'dt'
  Gaussian Naive Bayes: 'gnb'
  Logistic Regression: 'lgr'
  Gradient_Boosted_Trees: 'gbt'
constraints: # fairness constraints used for training different models
  Demografic Parity: 'DP'
  Equalized Odds: 'EO'
  Equality of Opportunity: 'TPRP'
  False Positive Rate Parity: 'FPRP'
  Error Rate Parity: 'ERP'
save: True # indicator if the results shoud be saved
