
data_path: 'data/synthetic42/Demo-b_Repay-b.csv'
results_dir: 'data/results/synthetic_test1/bb/'
weight_idx: 1
testset_size: 0.3
demo_ratio:
  - #Training
    - 0 #Black
    - 0 #White
  - #Testing
    - 0.5 #Black
    - 0.5 #White
  #Testing
label_ratio: # For Group Black
  - 0 #False 0
  - 0 #True 1
balance_test_set: True
set_bound:
  - 70000
  - 20000
models:
  Decision Tree: 'dt'
  Gaussian Naive Bayes: 'gnb'
  Logistic Regression: 'lgr'
  Gradient_Boosted_Trees: 'gbt'
constraints:
  Demografic Parity: 'DP'
  Equalized Odds: 'EO'
  Equality of Opportunity: 'TPRP'
  False Positive Rate Parity: 'FPRP'
  Error Rate Parity: 'ERP'
reduction_algorithms:
  Exponential Gradient: 'EG'
  Grid Search: 'GS'
save: True
