
data_path: 'data/final/balanced_set_200_2.csv'
results_dir: 'data/results/balanced_200_2/'
weight_idx: 1
testset_size: 0.3
demo_ratio:
  - #Training
    - 0.5 #Black
    - 0.5 #White
  - #Testing
    - 0.5 #Black
    - 0.5 #White
  #Testing
label_ratio: # For Black Group
  - 0.5 #False 0
  - 0.5 #True 1
balance_test_set: True
models:
  Decision Tree: 'dt'
  Gaussian Naive Bayes: 'gnb'
  Logistic Regression: 'lgr'
  Gradient_Boosted_Trees: 'gbt'
constraints:
  Demografic Parity: 'DP'
  Equalized Odds: 'EO'
  Equality of Opportunity: 'TPRP'
  False Positive Rate Parity: 'FPRP'
  Error Rate Parity: 'ERP'
reduction_algorithms:
  Exponential Gradient: 'EG'
  Grid Search: 'GS'
save: True
