
data_path: 'data/synthetic_ds/Demo-i_Repay-i.csv'
results_dir: 'results/synthetic_balTestSet/ii/'
weight_idx: 1
testset_size: 0.3
test_set_variant: 1 # 1= balanced testset 0= default 2= original,true FICO distribution
set_bound:
  - 70000
  - 30000
models:
  Decision Tree: 'dt'
  Gaussian Naive Bayes: 'gnb'
  Logistic Regression: 'lgr'
  Gradient_Boosted_Trees: 'gbt'
constraints:
  Demografic Parity: 'DP'
  Equalized Odds: 'EO'
  Equality of Opportunity: 'TPRP'
  False Positive Rate Parity: 'FPRP'
  Error Rate Parity: 'ERP'
save: True
