
data_dir: 'data/raw/'
result_path: 'data/synthetic42/Demo-u_Repay-o.csv'
order_of_magnitude: 100000
group_size_ratio:
  - 0.34
  - 0.66
black_label_ratio:
  - 0.34
  - 0.66
set_size: 100000
round_num_scores: 2
shuffle_seed: 42
