
data_dir: 'data/raw/'
result_path: 'data/synthetic42_2/Demo-u_Repay-b.csv'
order_of_magnitude: 100000
group_size_ratio:
  - 0.34 #black
  - 0.66 #white
black_label_ratio:
  - 0.5 #0
  - 0.5 #1
set_size: 100000
round_num_scores: 2
shuffle_seed: 42
