data_path: 'german_credit/german_data.csv'                        # path to the dataset csv-file
results_dir: 'german_credit/german_results/mit-reducts/' # directory to save the results

                                                                  # for reduction runs: 'german_credit/german_results/mit-reducts/
                                                                  # for cost-sens runs: 'german_credit/german_results/mit-costs/'
weight_idx: 1                                                     # weight index for samples (1 in our runs)
testset_size: 0.3                                                 # proportion of testset samples in the dataset
mitigated: 1                                                     # 0: unmitigated, 1: reductions, 2: cost_sensitive
balanced: True                                                   # this can be True if mitigated == 2
fp_weight: 6
fn_weight: 5
model_name: 'lgr'                                                 # classifier, 'dt' or 'lgr', used for training
reduction_algo: 'GS'                                              # exponentiated gradient, 'EG' or 'GS'
constraint_name: 'FPRP'                                            # fairness constraints used for reductions
                                                                  #Demographic Parity: 'DP'
                                                                  #Equalized Odds: 'EO'
                                                                  #Equality of Opportunity: 'TPRP'
                                                                  #False Positive Rate Parity: 'FPRP'
                                                                  #Error Rate Parity: 'ERP'
save: True                                                        # indicator if the results should be saved