data_path: 'german_credit/german_data.csv'                        # path to the dataset csv-file
results_dir: 'german_credit/german_results/testing_script_cost/' # directory to save the results
weight_idx: 1                                                     # weight index for samples (1 in our runs)
testset_size: 0.3                                                 # proportion of testset samples in the dataset
mitigated: 2                                                      # 0: unmitigated, 1: reductions, 2: cost_sensitive
balanced: False                                                   # this can be True if mitigated == 2
fp_weight: 2
fn_weight: 1
model_name: 'lgr'                                                 # classifier, 'dt' or 'lgr', used for training
constraint_name: 'TPRP'                                            # fairness constraints used for reductions
                                                                  #Demographic Parity: 'DP'
                                                                  #Equalized Odds: 'EO'
                                                                  #Equality of Opportunity: 'TPRP'
                                                                  #False Positive Rate Parity: 'FPRP'
                                                                  #Error Rate Parity: 'ERP'
save: True                                                        # indicator if the results should be saved